openapi: 3.0.3
info:
  title: Transaction Service API
  description: API para la gestión de transacciones bancarias
  version: 1.0.0
servers:
  - url: http://localhost:9095/api/v1
    description: Local development server
paths:
  /transactions/deposit:
    post:
      tags:
        - Transaction
      summary: Create a deposit transaction
      operationId: createDeposit
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DepositRequestDto'
      responses:
        '201':
          description: Deposit created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponseDto'

  /transactions/withdrawal:
    post:
      tags:
        - Transaction
      summary: Create a withdrawal transaction
      operationId: createWithdrawal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WithdrawalRequestDto'
      responses:
        '201':
          description: Withdrawal created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponseDto'

  /transactions/transfer:
    post:
      tags:
        - Transaction
      summary: Create a transfer transaction
      operationId: createTransfer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferRequestDto'
      responses:
        '201':
          description: Transfer created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponseDto'

  /transactions/payment:
    post:
      tags:
        - Transaction
      summary: Create a credit payment transaction
      operationId: createPayment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentRequestDto'
      responses:
        '201':
          description: Payment created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponseDto'

  /transactions/credit-charge:
    post:
      tags:
        - Transaction
      summary: Create a credit card charge transaction
      operationId: createCreditCharge
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditChargeRequestDto'
      responses:
        '201':
          description: Credit charge created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponseDto'

  /transactions:
    get:
      tags:
        - Transaction
      summary: Get all transactions
      operationId: getTransactions
      parameters:
        - name: accountId
          in: query
          schema:
            type: string
        - name: creditId
          in: query
          schema:
            type: string
        - name: startDate
          in: query
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          schema:
            type: string
            format: date
      responses:
        '200':
          description: List of transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransactionResponseDto'

  /transactions/products/{productId}/movements:
    get:
      tags:
        - Transaction
      summary: Get all movements for a specific product
      operationId: getProductMovements
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
        - name: productType
          in: query
          required: true
          schema:
            type: string
            enum: [ BANK_ACCOUNT, CREDIT, CREDIT_CARD ]
        - name: startDate
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: List of movements
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductMovementsResponseDto'

components:
  schemas:
    DepositRequestDto:
      type: object
      required:
        - targetAccountId
        - amount
      properties:
        targetAccountId:
          type: string
          description: Identificador de cuenta destino de deposito
        amount:
          type: number
          description: Monto de deposito
        feeAmount:
          type: number
          description: Monto de comision
        description:
          type: string
          description: Descripcion de deposito

    WithdrawalRequestDto:
      type: object
      required:
        - sourceAccountId
        - amount
      properties:
        sourceAccountId:
          type: string
          description: Identificador de cuenta origen de retiro
        amount:
          type: number
          description: Monto de retiro
        feeAmount:
          type: number
          description: Monto de comision
        description:
          type: string
          description: Descripcion de retiro

    TransferRequestDto:
      type: object
      required:
        - sourceAccountId
        - targetAccountId
        - amount
      properties:
        sourceAccountId:
          type: string
          description: Identificador de cuenta origen
        targetAccountId:
          type: string
          description: Identificador de cuenta destino
        amount:
          type: number
          description: Monto de transferencia
        description:
          type: string
          description: Descripcion de transferencia

    PaymentRequestDto:
      type: object
      required:
        - sourceAccountId
        - creditId
        - creditType
        - amount
      properties:
        sourceAccountId:
          type: string
          description: Identificador de cuenta origen
        creditId:
          type: string
          description: Identificador de producto de credito (Credito o Tarjeta de Credito)
        creditType:
          type: string
          enum: [CREDIT, CREDIT-CARD]
          description: Tipo de transaccion
        amount:
          type: number
          description: Monto de pago
        feeAmount:
          type: number
          description: Monto de comision
        description:
          type: string
          description: Descripcion de pago

    CreditChargeRequestDto:
      type: object
      required:
        - creditId
        - amount
        - totalInstallment
      properties:
        creditId:
          type: string
          description: Identificador de tarjeta de credito
        amount:
          type: number
          description: Monto de cargo
        totalInstallment:
          type: integer
          description: Numero de cuotas
        description:
          type: string
          description: Descripcion de cargo

    TransactionResponseDto:
      type: object
      properties:
        id:
          type: string
          description: Identificador de transaccion
        transactionType:
          type: string
          enum: [DEPOSIT, WITHDRAWAL, PAYMENT, CREDIT_CHARGE, TRANSFER]
          description: Tipo de transaccion
        productType:
          type: string
          enum: [BANK_ACCOUNT, CREDIT, CREDIT_CARD]
          description: Tipo de producto
        amount:
          type: number
          description: Monto de transaccion
        commission:
          type: number
          description: Comision por transaccion
        sourceAccountId:
          type: string
          description: Identificador de cuenta origen
        targetAccountId:
          type: string
          description: Identificador de cuenta destino
        creditId:
          type: string
          description: Identificador de producto de credito
        description:
          type: string
          description: Descripcion de transaccion
        status:
          type: string
          enum: [COMPLETED, FAILED]
          description: Status de transaccion
        transactionDate:
          type: string
          format: date-time
          description: Fecha de transaccion
        errorMessage:
          type: string
          description: Mensaje de error

    ProductMovementsResponseDto:
      type: object
      properties:
        productId:
          type: string
        productType:
          type: string
          enum: [BANK_ACCOUNT, CREDIT, CREDIT_CARD]
          description: Tipo de producto
        startDate:
          type: string
          format: date
          description: Fecha inicial de consulta
        endDate:
          type: string
          format: date
          description: Fecha final de consulta
        movements:
          type: array
          items:
            $ref: '#/components/schemas/TransactionResponseDto'
          description: lista de transacciones
        summary:
          $ref: '#/components/schemas/MovementsSummaryDto'


    MovementsSummaryDto:
      type: object
      properties:
        totalDeposits:
          type: number
          description: total de depositos
        totalWithdrawals:
          type: number
          description: total de retiros
        totalCommissions:
          type: number
          description: Total de comisiones
        totalMovements:
          type: integer
          description: Total de movimientos
        initialBalance:
          type: number
          description: Saldo inicial
        finalBalance:
          type: number
          description: Saldo final
